name: SPFx CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.20.2"

      - name: Install dependencies
        run: |
          npm ci
          npm i -g gulp

      - name: Bundle project
        run: gulp bundle --ship

      - name: Package solution
        run: gulp package-solution --ship

      - name: Deploy to SharePoint
        uses: pnp/action-cli-deploy-spfx@v1
        with:
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          TENANT: ${{ secrets.TENANT }}
          SITE: ${{ secrets.SITE }}
          PATH_TO_PACKAGE: "./sharepoint/solution/spfx-demo-app.sppkg"
