name: SPFx CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: |
          npm ci
          npm i -g gulp

      - name: Bundle project
        run: gulp bundle --ship

      - name: Package solution
        run: gulp package-solution --ship

      # CLI for Microsoft 365 login action
      - name: Login to tenant
        uses: pnp/action-cli-login@v2.2.1
        with:
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME}}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

      # CLI for Microsoft 365 deploy app action
      # Use either option 1 or option 2

      # Option 1 - Deploy app at tenant level
      - name: Option 1 - Deploy app to tenant
        id: climicrosoft365deploy # optional - use if output needs to be used
        uses: pnp/action-cli-deploy@v4
        with:
          APP_FILE_PATH: sharepoint/solution/spfx-demo-app.sppkg
          SKIP_FEATURE_DEPLOYMENT: true
          OVERWRITE: true
      # Option 1 - ends
      # Print the id of the app
      - name: Get the id of the app deployed
        run: echo "The id of the app deployed is ${{ steps.climicrosoft365deploy.outputs.APP_ID }}"
